global:
  scrape_interval: 15s # How often to collect metrics

scrape_configs:
  - job_name: "vehicleconnect-backend"
    static_configs:
      - targets: ["backend:8000"] # backend container internal name
    metrics_path: "/metrics"
